name: Bild
on: [push]
jobs:
  linux:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - run: |
               cmake -H. -B_build
               cmake --build _build
               
        - name: Configure and Build Project
          uses: threeal/cmake-action@v1.3.0
          
  windows:
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            
          - name: MSBuild
            uses: microsoft/setup-msbuild@v1.0.2
            
          - run: |
              mkdir _build
              cd _build
              cmake ..
              cmake --build .
              
          - name: Configure and Build Project
            uses: threeal/cmake-action@v1.3.0